#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
    path: /
    controller: App\Controller\ArticleController::home

app_logout:
    path: /logout
    methods: GET
